version: 2
  
models:
  - name: dim_listings_cleansed
    description: Cleansed dim table with listings
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 1000
          severity: error
    columns:
      - name: listing_id
        description: Primary key for the listing
        data_tests:
          - unique
          - not_null
      - name: host_id
        description: Foreign key for the hosts
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id
      - name: room_type
        data_tests:
          - accepted_values:
              arguments:
                values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
      - name: minimum_nights
        description: '{{ doc("dim_listings_cleansed__minimum_nights") }}'
        data_tests:
          - positive_values
  
  - name: dim_hosts_cleansed
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        description: "Host id"
        data_type: integer
      - name: host_name
        description: '{{ doc("dim_hosts_cleansed__host_name") }}'
        data_type: string
      - name: is_superhost
        data_type: boolean
      - name: updated_at
        data_type: timestamp
      - name: created_at
        data_type: timestamp
